project_name: tetragon-exec-logger

version: 2

builds:
  - id: skpr-tetragon-exec-logger
    main: cmd/tetragon-exec-logger/main.go
    binary: skpr-tetragon-exec-logger
    ldflags:
      - -extldflags '-static' -s -w
    env:
      - CGO_ENABLED=0
    goos: [ linux ]
    goarch: [ amd64, arm64 ]

archives:
  - ids:
    - none

checksum:
  disable: true

dockers:
  - dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/skpr/tetragon-exec-logger:v{{ .Version }}-amd64"
      - "ghcr.io/skpr/tetragon-exec-logger:latest-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    use: buildx

  - dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/skpr/tetragon-exec-logger:v{{ .Version }}-arm64"
      - "ghcr.io/skpr/tetragon-exec-logger:latest-arm64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    use: buildx
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/skpr/tetragon-exec-logger:v{{ .Version }}"
    image_templates:
      - "ghcr.io/skpr/tetragon-exec-logger:v{{ .Version }}-amd64"
      - "ghcr.io/skpr/tetragon-exec-logger:v{{ .Version }}-arm64"

  - name_template: "ghcr.io/skpr/tetragon-exec-logger:latest"
    image_templates:
      - "ghcr.io/skpr/tetragon-exec-logger:latest-amd64"
      - "ghcr.io/skpr/tetragon-exec-logger:latest-arm64"

changelog:
  use: github-native
